### ISSUE TITLE
app does not start

### ISSUE THREAD

**Issue by spookyfox** [imodeljs/desktop-starter#46]
I'm on Linux 20.04; Node 12.0. I cloned this repo, did npm i and npm start, but it won't start.
What can I do to fix this issue?

![Breitbandmesung](https://user-images.githubusercontent.com/14878872/107871999-1e302e80-6ea7-11eb-9b38-1741cd0bb65a.png)

**Comment by pmconne** [comment]
You mean Ubuntu 20.04, right? I confirmed I can run the app on Windows 10; I'll take it for a spin on Linux.

**Comment by pmconne** [comment]
I do not observe this assertion on Ubuntu 20.04 using Node 12.20.2 - `getIModelElectronApi` does not return `undefined`. (I do later observe the `getPassword` error referenced in #15).

`getIModelElectronApi` simply returns `window.imodeljs_api`, which is supposed to have been set by some preload script. I don't expect the exact Node version to be relevant, but assuming that's the only difference between our setups, would you mind trying it with Node 12.20.2?

**Comment by pmconne** [comment]
The electron initialization code changed significantly in the upcoming 2.12.0 version of iModel.js. You might want to try out the `updateTo2.12` branch to see if that resolves your problem.

**Comment by spookyfox** [comment]
> You mean Ubuntu 20.04, right? I confirmed I can run the app on Windows 10; I'll take it for a spin on Linux.

Yes, I mean Ubuntu :-)

**Comment by spookyfox** [comment]
> act Node version to be relevant, but assuming that's the only difference between our setups, would you mind trying it with Node 12.20.2?

I'm using Node 12.20.2, but it fails :-(

**Comment by spookyfox** [comment]
> I do not observe this assertion on Ubuntu 20.04 using Node 12.20.2 - `getIModelElectronApi` does not return `undefined`. (I do later observe the `getPassword` error referenced in #15).
> 
> `getIModelElectronApi` simply returns `window.imodeljs_api`, which is supposed to have been set by some preload script. I don't expect the exact Node version to be relevant, but assuming that's the only difference between our setups, would you mind trying it with Node 12.20.2?

Thanks for suggesting. But honestly I would not know, how to do an upgrade to this version. Maybe you can guide me?! Thanks in advance!

**Comment by pmconne** [comment]
> But honestly I would not know, how to do an upgrade to this version. Maybe you can guide me?!

```
curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by spookyfox** [comment]
Hi, Thanks for helping.
But unfortunately I don't get it working. Meanwhile I tried on Windows 10; NodeJS  12.3.0

I did as follows:
1. git clone https://github.com/imodeljs/desktop-starter.git
2. npm i
3. npm run start

The electron App starts, but is entirely empty.
If I go to localhost:3000 to use the browser version it fails:

![2021-02-16 11_45_33-Window](https://user-images.githubusercontent.com/14878872/108052539-984de800-704c-11eb-9bff-be3162ebc6c4.png)

Do you have any other idea how I could get it running for test purposes?

Thanks in advance,
Henrik

**Comment by pmconne** [comment]
> Do you have any other idea how I could get it running for test purposes?

We'll have to call in someone more familiar with this area of the code. @wgoehrig @kabentley @calebmshafer.

Meanwhile, you might try my suggestion of checking out the `updateTo2.12` branch and repeating `npm i` and `npm run start`. All of the electron IPC code changed significantly on that branch.

**Comment by spookyfox** [comment]
Thanks for your quick response. I don't know, but at least the electron version starts on windows. But the browser version still fails.
I'll try to use the 2.12 version as well and let you know if succeeded.
Why does the font look a bit strange actually?  
Thanks again.

**Comment by pmconne** [comment]
> I don't know, but at least the electron version starts on windows. But the browser version still fails.

There is no browser version. This is a desktop electron application.

On Windows, when you start the electron app, is there any output in the console? If so, what?

**Comment by spookyfox** [comment]
![image](https://user-images.githubusercontent.com/14878872/108062458-19f84280-705a-11eb-8da0-ba6d52afa9f7.png)

**Comment by spookyfox** [comment]
Than this note is a little bit miss leading:
![image](https://user-images.githubusercontent.com/14878872/108062570-46ac5a00-705a-11eb-8abd-82156abcb643.png)

Is there also a browser version available?
Thanks a lot!

**Comment by pmconne** [comment]
> this note is a little bit miss leading:

Yeah, that's courtesy of React.

> Is there also a browser version available?

There are a handful of sample browser-based iModel.js apps. @calebmshafer @Josh-Schifter what is the right one to start with?

**Comment by Josh-Schifter** [comment]
> There are a handful of sample browser-based iModel.js apps. @calebmshafer @Josh-Schifter what is the right one to start with?

https://www.itwinjs.org/learning/tutorials/develop-web-viewer/
