### ISSUE TITLE
× Unhandled Rejection (Error): Not running under Electron

### ISSUE THREAD

**Issue by farhantaj90** [imodeljs/desktop-starter#51]
×
Unhandled Rejection (Error): Not running under Electron this error is coming after running on localhost.

**Comment by apdevac** [comment]
Is there any update on this issue? I am also getting the same error and looking for a solution

**Comment by williamkbentley** [comment]
Alternatively, to `npm run start`, you can run: `npm run start:frontend` (to start the CRA web server) in one terminal and in another terminal: `npm run electron:debug` (to start the Electron window).

`npm run start` wraps those two scripts into one command.

**Comment by zly258** [comment]
![image](https://user-images.githubusercontent.com/26916479/121660253-b0eb7d80-cad5-11eb-8ed0-3e82f1c2dbde.png)
Report an error if you rotate the model

**Comment by williamkbentley** [comment]
My hunch is the backend did not get started correctly, but the error message was too quick to notice. As `npm run start` starts the frontend and backend in parallel, some of the logging can easily be missed. I re-wrote the way the backend is initialized w.r.t Client Id. I hope this will solve issues like this with clearer error messaging. If no more info is provided, I'm going to close this issue.
