### ISSUE TITLE
Signin process for opening online model is broken

### ISSUE THREAD

**Issue by griemens** [imodeljs/desktop-starter#53]
Clicking home icon and selecting open online model shows the signin page
And next clicking button "signin.signinbutton" the solution freezes.
This was working in the past when updating my application id.
Also tried to define contextid and modelid but it does not help.

Debugger shows no errors or warnings. It apears like no http request is made to bentley oidc.

Thanks

**Comment by williamkbentley** [comment]
We were working on some Electron authentication changes in this repo. Can you pull master and try again?

**Comment by griemens** [comment]
Thanks all working again from the master.
Now need to do some catchup on how the new login process works :) in the backend.

**Comment by williamkbentley** [comment]
Great. You can find some documentation in the [v2.14.0 change notes](https://www.itwinjs.org/changehistory/#authentication-changes-for-electron-and-mobile-apps). The upgrade PR ill likely also be helpful
