### ISSUE TITLE
Cannot read property 'x' of undefined at Function.createColumns

### ISSUE THREAD

**Issue by zly258** [imodeljs/desktop-starter#64]
![image](https://user-images.githubusercontent.com/26916479/121660558-f4de8280-cad5-11eb-91a0-877eee41522d.png)
Report an error if you rotate the model

**Comment by pmconne** [comment]
Thanks for reporting this. This problem was fixed in imodeljs-frontend 2.16.0. @williamkbentley any plans to upgrade from 2.15.0?

**Comment by zly258** [comment]
extremely grateful
