### ISSUE TITLE
Failed to package exe with desktop starter electron

### ISSUE THREAD

**Issue by shenshengyi** [imodeljs/desktop-starter#69]
Hi, I'm using the command build:dist The attempt to package the desktop starter into exe failed. The error is as follows:
 **Error: Application entry file "build\app\main.js" in the "D:\DeskStarter\desktop-starter\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.**

**Comment by shenshengyi** [comment]
It has been resolved.

**Comment by williamkbentley** [comment]
Can you share what you needed to do?
