### ISSUE TITLE
Cannot debug using vscode

### ISSUE THREAD

**Issue by kardoka** [imodeljs/desktop-starter#80]
Greetings, the [debugging section](https://github.com/imodeljs/desktop-starter/blob/master/README.md#debugging) in the readme seems to be outdated. There does not seem to be a "Watch All" option in "Terminal" -> "Run Task" or a "Electron: All" debug configuration.

For the tasks, the only two watch tasks are:
- `tsc: watch - tsconfig.json`
- `tsc: watch - tsconfig.backend.json`

For debug configurations, the only electron option is "Electron: Main". There is no "Electron: All" option. 

What are the options for debugging this code? Have I missed something?

**Comment by williamkbentley** [comment]
I cannot reproduce your problem. The `Watch All` task is in [tasks.json](https://github.com/imodeljs/desktop-starter/blob/master/.vscode/tasks.json#L27). The `Electron: All` debug compound is in [launch.json](https://github.com/imodeljs/desktop-starter/blob/795c440218a1bd95867089d97f8a9948d22aec08/.vscode/launch.json#L34). In my testing I was able to debug frontend and backend code using these two configurations. 

Perhaps your version of VSCode does not support compounds and `dependsOn` tasks? You could also try clicking "Go back" or "Show All Tasks..." at the bottom of the task select dialog.

**Comment by kardoka** [comment]
I used the the .json files that @williamkbentley mentioned and it works fine now, thank you! It seems that VSCode did not generate the correct config files in .vscode/. I checked the version and it is the latest one as of now (1.60.0), so the issue should be elsewhere.

**Comment by williamkbentley** [comment]
Great! Maybe your branch is behind master from when those debug configuration files were created. I believe VSCode reads them directly.
